SportsStore/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components;

public class CartSummaryViewComponent : ViewComponent
{
	readonly Cart _cart;

	public CartSummaryViewComponent(Cart cart) => _cart = cart;

	public IViewComponentResult Invoke() => View(_cart);
}

SportsStore/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Components;

public class NavigationMenuViewComponent : ViewComponent
{
	readonly IStoreRepository _repository;

	public NavigationMenuViewComponent(IStoreRepository repository) =>
		_repository = repository;

	public IViewComponentResult Invoke()
	{
		// ReSharper disable once ConditionalAccessQualifierIsNonNullableAccordingToAPIContract
		ViewBag.SelectedCategory = RouteData?.Values["category"]!;

		return View(_repository.Products
			.Select(x => x.Category).Distinct().OrderBy(x => x));
	}
}

SportsStore/Views/Shared/ProductSummary.cshtml
@model Product

<div class="card border-secondary m-1 p-1">

	<div class="bg-light p-1">
		<h4>
			@Model.Name
			<span class="badge rounded-pill bg-primary text-white float-end">
				<small>@Model.Price.ToString("C")</small>
			</span>
		</h4>
	</div>

	<form id="@Model.ProductID" asp-page="/cart" method="post">
		<input type="hidden" asp-for="ProductID" />
		<input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
		<span class="card-text p-1">
			@Model.Description
			<button type="submit" class="btn btn-success btn-sm float-end">Add To Cart</button>
		</span>
	</form>

</div>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="en">

<head>

	<link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
	<link href="/lib/font-awesome/css/all.min.css" rel="stylesheet">
	<meta charset="UTF-8">
	<meta name="viewport" content="initial-scale=1.0, width=device-width">
	<title>SportsStore</title>

</head>

<body>

<!-- Заголовок -->

<div class="bg-dark text-white p-2">
	<div class="container-fluid">
		<div class="row align-items-center">
			<div class="col navbar-brand">SPORTS STORE</div>
			<div class="col-6 navbar-text text-end">
				<vc:cart-summary />
			</div>
		</div>
	</div>
</div>

<!-- # Заголовок -->

<!-- Тело -->

<div class="row m-1 p-1">

<!-- Меню -->

<div class="col-3" id="categories">

<vc:navigation-menu/>

</div>

<!-- # Меню -->

<!-- Контент -->

<div class="col-9">

@RenderBody()

</div>

<!-- # Контент -->

</div>

<!-- # Тело -->

</body>

</html>