SportsStore/Models/Cart.cs
namespace SportsStore.Models;

public class Cart
{
	public List<CartLine> Lines { get; set; } = new();

	public virtual void AddItem(Product product, int quantity)
	{
		var line = Lines.FirstOrDefault(
			x => x.Product.ProductID == product.ProductID);

		if (line is null)
		{
			Lines.Add(new() { Product = product, Quantity = quantity });
		}
		else
		{
			line.Quantity += quantity;
		}
	}

	public virtual void Clear() => Lines.Clear();

	public decimal ComputeTotalValue() =>
		Lines.Sum(x => x.Product.Price * x.Quantity);

	public virtual void RemoveLine(Product product) =>
		Lines.RemoveAll(x => x.Product.ProductID == product.ProductID);
}

SportsStore/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using SportsStore.Models;

namespace SportsStore.Controllers;

public class OrderController : Controller
{
	readonly Cart _cart;

	readonly IOrderRepository _repository;

	public OrderController(IOrderRepository repository, Cart cart)
	{
		_cart = cart;
		_repository = repository;
	}

	public ViewResult Checkout() => View(new Order());

	[HttpPost]
	public IActionResult Checkout(Order order)
	{
		if (_cart.Lines.Count == 0)
			ModelState.AddModelError(string.Empty, "Sorry, your cart is empty!");

		if (!ModelState.IsValid) return View();

		order.Lines = _cart.Lines;
		_repository.SaveOrder(order);
		_cart.Clear();

		return RedirectToPage("/completed", new { orderId = order.OrderID });
	}
}

SportsStore/Pages/Cart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SportsStore.Models;

namespace SportsStore.Pages;

public class CartModel : PageModel
{
	readonly IStoreRepository _repository;

	public CartModel(IStoreRepository repository, Cart cart)
	{
		_repository = repository;
		Cart = cart;
	}

	public Cart Cart { get; private set; }

	public string ReturnUrl { get; private set; } = "/";

	public void OnGet(string returnUrl) => ReturnUrl = returnUrl;

	public IActionResult OnPost(long productId, string returnUrl)
	{
		var product = _repository.Products.FirstOrDefault(
			x => x.ProductID == productId);

		if (product is not null) Cart.AddItem(product, 1);

		return RedirectToPage(new { returnUrl });
	}

	public IActionResult OnPostRemove(long productId, string returnUrl)
	{
		Cart.RemoveLine(Cart.Lines.First(
			x => x.Product.ProductID == productId).Product);

		return RedirectToPage(new { returnUrl });
	}
}

SportsStore/Pages/Cart.cshtml
@page
@model CartModel

<h2>Your cart</h2>

<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th class="text-center">Quantity</th>
			<th class="text-start">Item</th>
			<th class="text-end">Price</th>
			<th class="text-end">Subtotal</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var line in Model.Cart.Lines)
		{
			<tr>
				<td class="text-center">@line.Quantity</td>
				<td class="text-start">@line.Product.Name</td>
				<td class="text-end">@line.Product.Price.ToString("C")</td>
				<td class="text-end">@line.ComputeSubtotalValue().ToString("C")</td>
				<td class="text-center">
					<form asp-page-handler="Remove" method="post">
						<input type="hidden" name="ProductID" value="@line.Product.ProductID" />
						<input type="hidden" name="ReturnUrl" value="@Model.ReturnUrl" />
						<button type="submit" class="btn btn-sm btn-danger">Remove</button>
					</form>
				</td>
			</tr>
		}
	</tbody>
	<tfoot>
		<tr>
			<td class="text-end" colspan="3">Total:</td>
			<td class="text-end">@Model.Cart.ComputeTotalValue().ToString("C")</td>
		</tr>
	</tfoot>
</table>

<div class="text-center">
	<a class="btn btn-primary" href="@Model.ReturnUrl">Continue shopping</a>
	<a class="btn btn-primary" asp-controller="Order" asp-action="Checkout">Checkout</a>
</div>

SportsStore/Pages/Completed.cshtml
@page

<div class="text-center">
	<h2>Thanks!</h2>
	<p>Thanks for placing order #@OrderId.</p>
	<p>We'll ship your goods as soon as possible.</p>
	<a class="btn btn-primary" asp-controller="Home">Return to Store</a>
</div>

@functions
{
	[BindProperty(SupportsGet = true)]
	public string? OrderId { get; set; }
}

SportsStore/Pages/_CartLayout.cshtml
<!DOCTYPE html>

<html lang="en">

<head>

	<link href="/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet">
	<meta charset="UTF-8">
	<meta name="viewport" content="initial-scale=1.0, width=device-width">
	<title>SportsStore</title>

</head>

<body>

<div class="bg-dark text-white p-2">
	<span class="navbar-brand ms-2">SPORTS STORE</span>
</div>

<div class="m-1 p-1">
	@RenderBody()
</div>

</body>

</html>